import assert from 'node:assert/strict';import fs from 'node:fs';
import {dispatchUnifiedFactory455,completeUnifiedFactoryWork455,unifiedDesignWorkView455} from './route.mjs';
const tests=[];async function t(name,f){try{await f();tests.push({name,passed:true})}catch(e){tests.push({name,passed:false,error:e.message})}}
function fixture(){const rows=[{id:'w1',kind:'work',owner:'o1',state:'running',data:{conversation_id:'c1',message:'هدف'}}];return {rows,get:async id=>structuredClone(rows.find(r=>r.id===id)),list:async(k,key)=>structuredClone(rows.filter(r=>r.kind===k&&r.key===key)),create:async(kind,key,state,data)=>{const r={id:'r'+rows.length,kind,key,state,data,owner:'o1'};rows.push(r);return structuredClone(r)},update:async(id,state,data)=>{const i=rows.findIndex(r=>r.id===id);rows[i]={...rows[i],state,data};return structuredClone(rows[i])}}}
async function dispatch(state,fetchImpl=async()=>({ok:true})){return dispatchUnifiedFactory455({state,work:await state.get('w1'),ownerId:'o1',goal:'هدف',signingSecret:'fixture',sign:(v,k)=>'signed',fetchImpl})}
await t('Old entry dispatches same dynamic designer and binds original work',async()=>{const state=fixture();let sent;await dispatch(state,async(url,opts)=>{sent={url,body:JSON.parse(opts.body)};return{ok:true}});assert.ok(sent.url.includes('vtIB0yqp'));assert.equal(sent.body.op,'design_worker');assert.equal(sent.body.payload.owner,'o1');const d=state.rows[1];assert.equal(d.data.sourceWorkId,'w1');assert.equal(d.data.conversation_id,'c1');assert.equal((await state.get('w1')).data.design_id,d.id);assert.equal(d.data.available_systems,undefined)});
await t('Retry reuses design and preserves original goal',async()=>{const s=fixture();await dispatch(s);await dispatch(s);assert.equal(s.rows.filter(r=>r.kind==='employee_design_preview').length,1);s.rows[1].data.goal='different';await assert.rejects(()=>dispatch(s),/design_mismatch/)});
await t('Network ambiguity remains pending, never success',async()=>{const s=fixture();const r=await dispatch(s,async()=>{throw Error('timeout')});assert.equal(r.dispatch,'unconfirmed');assert.equal((await s.get('w1')).state,'running')});
await t('Foreign owner is rejected before writes or network',async()=>{const s=fixture();await assert.rejects(async()=>dispatchUnifiedFactory455({state:s,work:await s.get('w1'),ownerId:'foreign',goal:'x',signingSecret:'fixture'}));assert.equal(s.rows.length,1)});
await t('Terminal work is not reopened',async()=>{const s=fixture();const work=await s.get('w1');s.rows[0].state='cancelled';const r=await dispatchUnifiedFactory455({state:s,work,ownerId:'o1',goal:'x',signingSecret:'x'});assert.equal(r.work_status,'cancelled');assert.equal(s.rows.length,1)});
for(const status of ['awaiting_connections','needs_configuration','failed'])await t('Parent receives '+status+' with saved conversation result',async()=>{const s=fixture();await dispatch(s);const d=s.rows[1];d.state=status;d.data.plan={name:'اختبار'};d.data.built={structureVerified:true,status:'DISABLED'};if(status!=='failed'){d.data.employeeId='e1';s.rows.push({id:'e1',owner:'o1',kind:'employee',data:{sourceDesignId:d.id,contract:{goal:'هدف'},flowId:null}})}const r=await completeUnifiedFactoryWork455({state:s,design:d,view:unifiedDesignWorkView455(d)});assert.equal(r.state,status==='awaiting_connections'?'succeeded':status==='failed'?'failed':'awaiting_input');assert.deepEqual(r.data.result455.recent_work,[]);assert.equal(s.rows.filter(r=>r.kind==='message').length,1);await completeUnifiedFactoryWork455({state:s,design:d,view:unifiedDesignWorkView455(d)});assert.equal(s.rows.filter(r=>r.kind==='message').length,1)});
await t('Mismatched employee cannot complete work',async()=>{const s=fixture();await dispatch(s);const d=s.rows[1];d.state='needs_configuration';d.data.employeeId='e';s.rows.push({id:'e',kind:'employee',owner:'other',data:{}});await assert.rejects(()=>completeUnifiedFactoryWork455({state:s,design:d,view:{status:'awaiting_input',reply:'x'}}),/employee_mismatch/);assert.equal((await s.get('w1')).state,'running')});
await t('Unfinished design cannot finalize parent',async()=>{const s=fixture();await dispatch(s);const r=await completeUnifiedFactoryWork455({state:s,design:s.rows[1],view:{status:'succeeded'}});assert.equal(r.state,'running')});
for(const n of ['worker','gateway','preview']){const code=fs.readFileSync(new URL(n+'.js',import.meta.url),'utf8');await t(n+' parses with integration',()=>{new Function(code.replaceAll('export ',''));});}
const report={passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,tests};fs.writeFileSync(new URL('test-results.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
