(()=>{'use strict';
const $=selector=>document.querySelector(selector);let current=null;
const esc=value=>String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const loadRuns=()=>{try{return JSON.parse(localStorage.getItem('siyadah-dev-lab-runs')||'[]')}catch{return []}};
const saveRuns=runs=>localStorage.setItem('siyadah-dev-lab-runs',JSON.stringify(runs.slice(0,20)));
async function api(path,options){const response=await fetch(path,options),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'تعذرت التجربة');return data}
function renderContext(context){$('#context').innerHTML=`<span>اللقطة: ${esc(context.snapshot)}</span><span>المعرفة: ${context.knowledge.facts.length}</span><span>الموظفون: ${context.employees.length}</span><span>الأدوات المتاحة للمحاكاة: ${context.tools.length}</span>`}
function render(run){current=run;$('#results').innerHTML=run.results.map(result=>`<article class="card" data-win="${run.winner===result.mode}"><h2>${esc(result.label)}</h2><div class="answer">${esc(result.reply)}</div><div class="meta">${(result.durationMs/1000).toFixed(1)}ث · ${Number(result.usage.total_tokens||0)} وحدة · ${esc(result.model)}</div><button class="pick" data-mode="${result.mode}" aria-pressed="${run.winner===result.mode}">${run.winner===result.mode?'الفائز':'اختره'}</button></article>`).join('');$('#export').classList.toggle('on',Boolean(run.winner));}
function renderHistory(){const runs=loadRuns();$('#history').innerHTML=runs.length?runs.map(run=>`<button data-id="${run.id}">${esc(run.scenario.slice(0,120))}${run.winner?' · فائز محدد':''}</button>`).join(''):'<span class="status">لا توجد تجارب محفوظة محليًا.</span>'}
async function runAll(event){event.preventDefault();const button=$('#run'),scenario=$('#scenario').value.trim(),customInstruction=$('#custom').value.trim();button.disabled=true;$('#status').textContent='نشغّل المتغيرات الثلاثة على نفس اللقطة…';const run={id:crypto.randomUUID(),createdAt:new Date().toISOString(),scenario,customInstruction,winner:null,results:[]};try{for(const mode of ['free','guided','custom']){const data=await api('/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,scenario,customInstruction})});run.results.push(data.result);render(run)}const runs=[run,...loadRuns()];saveRuns(runs);renderHistory();$('#status').textContent='اكتملت المقارنة. اختر الفائز فقط؛ لم يتغير الإنتاج.'}catch(error){$('#status').textContent=error.message}finally{button.disabled=false}}
$('#form').addEventListener('submit',runAll);$('#results').addEventListener('click',event=>{const button=event.target.closest('[data-mode]');if(!button||!current)return;current.winner=button.dataset.mode;const runs=loadRuns(),index=runs.findIndex(run=>run.id===current.id);if(index>=0)runs[index]=current;else runs.unshift(current);saveRuns(runs);render(current);renderHistory()});
$('#history').addEventListener('click',event=>{const button=event.target.closest('[data-id]'),run=button&&loadRuns().find(item=>item.id===button.dataset.id);if(run)render(run)});
$('#export').addEventListener('click',()=>{if(!current?.winner)return;const winner=current.results.find(result=>result.mode===current.winner),request={kind:'siyadah_developer_change_request',createdAt:new Date().toISOString(),scenario:current.scenario,winner:{mode:winner.mode,instruction:winner.instruction,model:winner.model},evidence:{snapshot:winner.snapshot,durationMs:winner.durationMs,usage:winner.usage,output:winner.reply},status:'proposal_only',productionChanged:false};const blob=new Blob([JSON.stringify(request,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`siyadah-change-request-${current.id}.json`;link.click();URL.revokeObjectURL(link.href)});
api('/api/context').then(data=>renderContext(data.context)).catch(error=>{$('#status').textContent=error.message});renderHistory();
})();
