server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location /siyadah-api/ {
    proxy_ssl_server_name on;
    proxy_set_header Host siyadah-core-api-production.up.railway.app;
    proxy_set_header Origin $http_origin;
    proxy_pass https://siyadah-core-api-production.up.railway.app/;
  }
  location ~* \.(?:html|js|css)$ {
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }
  location ~* \.(?:png|jpg|jpeg|gif|svg|ico|webp|woff2?|ttf|eot|json|txt|xml)$ {
    add_header Cache-Control "public, max-age=86400, must-revalidate";
    try_files $uri =404;
  }
  location / {
    add_header Cache-Control "no-cache";
    try_files $uri $uri/ /404.html =404;
  }
}
