(()=>{'use strict';
 const endpoint='https://activepieces-p8l1-455.up.railway.app/api/v1/webhooks/vtIB0yqpB3lMK3ykTSTgN/sync';
 const el=(t,text)=>{let n=document.createElement(t);if(text)n.textContent=text;return n;};let busy=false,requestId=null,timer=null;
 const panel=el('dialog');panel.dir='rtl';panel.style.cssText='width:min(940px,92vw);max-height:88vh;overflow:auto;border:1px solid #ddd;border-radius:16px;padding:24px;font:16px system-ui;line-height:1.7;background:white;color:#222';
 const title=el('h2','موظفوك — التصميم والربط');const close=el('button','إغلاق');const intro=el('p','نختار عمليات الأدوات حسب هدفك ومعرفة شركتك، ونحفظ الموظف مع خطواته ومتطلبات ربطه.');const label=el('label','هدف الموظف');const goal=el('textarea');goal.rows=3;goal.style.cssText='display:block;width:100%;font:inherit;margin:10px 0';goal.setAttribute('aria-label','هدف الموظف');label.append(goal);const create=el('button','ابنِ الموظف');const status=el('p');status.setAttribute('role','status');const list=el('div');panel.append(title,close,intro,label,create,status,list);document.body.append(panel);
 const open=el('button','الموظفون والربط');open.style.cssText='position:fixed;top:12px;left:80px;z-index:40;background:#126b4a;color:white;border:0;border-radius:10px;padding:10px 16px;font:15px system-ui;cursor:pointer';document.body.append(open);
 for(const b of [create,close])b.style.cssText='padding:8px 15px;border:1px solid #ccc;border-radius:8px;background:#f5f6f5;font:inherit;cursor:pointer';
 async function req(body){const token=localStorage.getItem('siyadah_token');if(!token)throw Error('session_required');const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body),signal:AbortSignal.timeout(25000)});const d=await r.json();if(!r.ok||!d.ok)throw Error('request_failed');return d;}
 const states={routing:'فهم الرسالة والسياق',selecting_operations:'اختيار العمليات المناسبة للهدف',queued:'في قائمة البناء',understanding:'فهم الهدف ومعرفة الشركة',loading_contracts:'التحقق من مواصفات الأدوات',normalizing_response:'تنظيم الخطة للتحقق منها',discovering:'البحث عن العمليات المناسبة',repairing:'تصحيح الخطة بعد التحقق',planning:'تركيب خطوات الموظف',building:'بناء مسودة الموظف',validating:'مراجعة تغطية الهدف والحقول',verifying:'التحقق من الخطوات المحفوظة',awaiting_connections:'بانتظار ربط الحسابات',needs_configuration:'يحتاج استكمال الإعداد',failed:'تعذّر إكمال البناء'};
 function render(employees){list.replaceChildren();if(!employees.length)list.append(el('p','لم تُنشئ موظفًا في هذا المسار بعد.'));
  const newest=new Map();for(const e of [...employees].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))))if(!newest.has(e.goal))newest.set(e.goal,e);
  for(const e of newest.values()){const p=e.plan;const card=el('article');card.style.cssText='border:1px solid #ddd;border-radius:12px;padding:18px;margin:16px 0';card.append(el('h3',p?.name||'موظف قيد البناء'),el('strong',states[e.status]||e.status),el('p',e.goal));
   if(p){if(p.strategy){for(const [key,label]of [['business_type','نشاط الشركة'],['target_customer','الجمهور'],['marketing_type','نوع التسويق'],['funnel','مسار العميل'],['success_metric','مؤشر النجاح']]){const value=p.strategy[key];if(value)card.append(el('p',label+': '+(typeof value==='string'?value:JSON.stringify(value))));}}const profile=p.knowledge?.website?.companyProfile||p.knowledge?.companyProfile;if(profile?.website)card.append(el('p','معرفة الشركة من: '+profile.website));const steps=el('ol');for(const s of p.selected||[]){const item=el('li');item.append(el('b',s.reason),el('div',s.pieceName.replace('@activepieces/piece-','')+' · '+(s.actionName||s.triggerName)));steps.append(item);}card.append(steps);
    const details=el('details'),summary=el('summary','متطلبات الربط ودليل النجاح');details.append(summary);for(const b of p.bindings||[])details.append(el('p',(b.type==='connection'?'حساب: ':'إعداد من الحساب: ')+(b.label||b.property)));for(const v of p.evidence||[])details.append(el('p','النجاح: '+v.metric+' — '+v.check));for(const v of [...(p.missing||[]),...(p.issues||[])])details.append(el('p','ناقص: '+(typeof v==='string'?v:JSON.stringify(v))));card.append(details);
    card.append(el('p',e.built?.structureVerified?'تم التحقق من حفظ خطوات المسودة. التنفيذ الخارجي ينتظر الربط والاختبار.':'لم يثبت اكتمال بناء Flow لهذا الموظف بعد.'));
   }if(e.error)card.append(el('p','سبب التعثر: '+e.error));list.append(card);
  }
 }
 async function refresh(){clearTimeout(timer);try{const d=await req({op:'design_list'});render(d.employees);if(d.employees.some(e=>!['awaiting_connections','needs_configuration','failed'].includes(e.status)))timer=setTimeout(refresh,10000);}catch{status.textContent='تعذّر تحديث الموظفين. أعد فتح القائمة للتحقق.';}}
 open.onclick=()=>{panel.showModal();refresh();};close.onclick=()=>panel.close();
 create.onclick=async()=>{if(busy||goal.value.trim().length<2){status.textContent='اكتب هدفًا واضحًا للموظف.';return;}busy=true;create.disabled=true;requestId=requestId||crypto.randomUUID();status.textContent='جارٍ حفظ طلب البناء…';try{await req({op:'design_start',goal:goal.value.trim(),request_id:requestId});requestId=null;status.textContent='حُفظ الطلب. يمكنك متابعة الموظف هنا والعودة لاحقًا.';refresh();}catch{status.textContent='لم نتأكد من قبول الطلب. المحاولة التالية تستخدم رقم الطلب نفسه لمنع تكراره.';}finally{busy=false;create.disabled=false;}};
 window.addEventListener('pagehide',()=>clearTimeout(timer));refresh();
})();
