import assert from 'node:assert/strict';import fs from'node:fs';import crypto from'node:crypto';
import{makeCatalogContract,outputPaths,verifyCatalogContract}from'./catalog-contract.mjs';
import{indexCatalog,retrieveCatalog}from'./catalog-selector.mjs';
import{validateDesign,designEmployee455,expandOperationMenu455}from'../employee-design/factory-design.mjs';
const rows=JSON.parse(fs.readFileSync(new URL('catalog-enriched.json',import.meta.url))), registry=JSON.parse(fs.readFileSync(new URL('live-registry.json',import.meta.url)));
const originals=JSON.parse(fs.readFileSync(new URL('../employee-design/catalog-rows.json',import.meta.url)));
const checks=[];function check(name,fn){fn();checks.push(name);}
check('All 764 editorial records preserved; contracts pin source and version',()=>{assert.equal(rows.length,764);rows.forEach((r,i)=>{for(const [k,v]of Object.entries(originals[i]))assert.deepEqual(r[k],v);const c=JSON.parse(r.operations_v1);assert.equal(c.piece,r.piece);assert.equal(c.version,r.contract_version);assert.equal(crypto.createHash('sha256').update(r.operations_v1).digest('hex'),r.contract_hash);assert.equal(c.business_outcome_verified,false);});});
const index=indexCatalog(rows,registry);
check('7201 distinct native operations indexed without silently losing human-audience flow operations',()=>{assert.equal(index.documents.length,7201);assert.equal(new Set(index.documents.map(d=>d.key)).size,7201);assert.equal(index.invalid.length,0);});
check('Nested outputs use value override, key fallback, and arrays',()=>{assert.deepEqual(outputPaths({fields:[{key:'display',value:'message.subject'},{key:'updates',children:[{key:'updatedRows'}]},{key:'items',listItems:[{key:'id'}]}]}),['message.subject','updates','updates.updatedRows','items','items[].id']);});
check('Stale and mismatched versions are excluded',()=>{const stale={...rows[0],contract_checked_at:'2020-01-01T00:00:00Z'};const p=registry.find(p=>p.name===stale.piece);assert.equal(verifyCatalogContract(stale,p).ok,false);assert.equal(indexCatalog([stale],registry).documents.length,0);assert.equal(verifyCatalogContract(rows[0],{...p,version:'999.0.0'}).ok,false);});
check('Duplicate catalog identities fail closed',()=>assert.throws(()=>indexCatalog([rows[0],rows[0]],registry),/duplicate/));
for(const [kind,query,piece,expected]of [['action','create card Trello','trello','create_card'],['action','append row spreadsheet','google-sheets','insert_row'],['trigger','new email Gmail','gmail','gmail_new_email_received'],['action','send template message WhatsApp','whatsapp','send-template-message']])check('Native contract retrieval: '+expected,()=>assert.equal(retrieveCatalog(index,{kind,query,explicitPiece:'@activepieces/piece-'+piece,limit:1})[0]?.name,expected));
check('Related-operation inspection exposes Mailchimp send after create',()=>{const menu=expandOperationMenu455(index,[{pieceName:'@activepieces/piece-mailchimp',key:'@activepieces/piece-mailchimp:action:create_campaign'}]);assert.ok(menu.some(x=>x.name==='send_campaign'));assert.ok(menu.some(x=>x.name==='get_campaign_report'));});
check('Facebook Leads does not claim advertising campaign creation',()=>assert.equal(retrieveCatalog(index,{kind:'action',query:'create paid advertising campaign',explicitPiece:'@activepieces/piece-facebook-leads'}).length,0));
const contracts=[{pieceName:'source',kind:'trigger',name:'new',version:'1',props:{},outputSchema:{fields:[{key:'email'}]}},{pieceName:'sink',kind:'action',name:'save',version:'1',props:{value:{type:'SHORT_TEXT',required:true},budget:{type:'NUMBER',required:false},resource:{type:'DROPDOWN',required:true}},outputSchema:{fields:[{key:'id'}]},authRequired:true}];
const goal='احفظ البريد';const basis={source:'user_goal',quote:goal};const needs=[{id:'receive'},{id:'save'}];const plan=()=>({original_goal:goal,name:'test',trigger:{pieceName:'source',triggerName:'new',input:{},covers:['receive'],reason:'receive',context_basis:basis},steps:[{pieceName:'sink',actionName:'save',input:{value:'{{trigger.email}}'},covers:['save'],reason:'save',context_basis:basis}],bindings:[{step:'step_1',property:'resource',type:'account_resource'}],missing:[],assumptions:[],evidence:[{step:'step_1',metric:'saved record',check:'read record id',output_path:'id'}]});
check('Only account bindings can remain before connection',()=>assert.equal(validateDesign(plan(),needs,contracts,goal).status,'awaiting_connections'));
check('Business budget cannot be disguised as account binding',()=>{const p=plan();p.bindings.push({step:'step_1',property:'budget',type:'account_resource'});assert.equal(validateDesign(p,needs,contracts,goal).status,'needs_configuration');});
check('Fabricated company context cannot justify selection',()=>{const p=plan();p.steps[0].context_basis={source:'company_context',quote:'invented company fact'};assert.throws(()=>validateDesign(p,needs,contracts,goal,{}),/selection_context_unproven/);});
check('Undocumented output cannot be silently accepted',()=>{const cs=structuredClone(contracts);delete cs[0].outputSchema;assert.equal(validateDesign(plan(),needs,cs,goal).status,'needs_configuration');});
check('Incorrect evidence path cannot mark design ready',()=>{const p=plan();p.evidence[0].output_path='revenue';assert.equal(validateDesign(p,needs,contracts,goal).status,'needs_configuration');});
check('Binding cannot cross steps or pieces',()=>{const p=plan();p.bindings[0].pieceName='other';assert.throws(()=>validateDesign(p,needs,contracts,goal),/binding_piece_mismatch/);p.bindings[0].step='step_9';assert.throws(()=>validateDesign(p,needs,contracts,goal),/binding_step_unknown/);});
// Integration fixture: real saved native metadata + actual generic pipeline. The AI is a deterministic fixture, not a live intelligence evaluation.
const actualFetch=globalThis.fetch;const prompts=[],phases=[];let fetchAttempts=0;
const actualGoal='حوّل كل بريد Gmail جديد إلى بطاقة Trello';
const actualBasis={source:'user_goal',quote:actualGoal};
const query={original_goal:actualGoal,needs:[{id:'map',kind:'mapping',capability:'Map message fields to card fields',search_terms:[],required:true},{id:'in',kind:'trigger',capability:'new incoming Gmail email',system_hint:null,search_terms:['new email Gmail'],required:true},{id:'out',kind:'action',capability:'create Trello card',system_hint:null,search_terms:['create card Trello'],required:true},{id:'proof',kind:'verification',capability:'read Trello card details',system_hint:null,search_terms:['get card Trello'],required:true}],strategy:{business_type:'test',assumptions:[]},success_criteria:['A card saved with email content'],missing:[]};
const proposed={original_goal:actualGoal,name:'Email to card',trigger:{pieceName:'@activepieces/piece-gmail',triggerName:'gmail_new_email_received',input:{},covers:['in'],reason:'receive',context_basis:actualBasis},steps:[{pieceName:'@activepieces/piece-trello',actionName:'create_card',input:{name:'{{trigger.message.subject}}',description:'{{trigger.message.text}}'},covers:['out','proof','map'],reason:'record',context_basis:actualBasis}],bindings:[{step:'trigger',property:'auth',type:'connection'},{step:'step_1',property:'auth',type:'connection'},{step:'step_1',property:'board_id',type:'account_resource'},{step:'step_1',property:'list_id',type:'account_resource'}],evidence:[{step:'step_1',metric:'Card created',check:'Card id is returned',output_path:'id'}],missing:[],assumptions:[]};
try{
 globalThis.fetch=async url=>{if(++fetchAttempts===1)throw Error('fetch failed');const u=new URL(url);if(u.pathname==='/api/v1/pieces')return{ok:true,json:async()=>registry};const name=decodeURIComponent(u.pathname.split('/').at(-1));return{ok:true,json:async()=>JSON.parse(fs.readFileSync(new URL('pieces/'+name.split('/').at(-1)+'.json',import.meta.url)))};};
 let businessFixtureIssues=[];
 const call=async(name,args)=>{if(name==='ap_run_action'){if(args.input.schema?.fields.required?.length===1&&args.input.schema.fields.required[0]==='issues')return{content:[{type:'text',text:'✅ Result\n\n'+JSON.stringify({issues:businessFixtureIssues})}]};if((args.input.text||args.input.prompt).includes('{{'))throw Error('Future flow references must not be resolved by the planner action');prompts.push(args.input.text||args.input.prompt);if((args.input.text||'').startsWith('Repair the operation choice'))return{content:[{type:'text',text:'✅ Result\n\n'+JSON.stringify({selected:[],gaps:query.needs.filter(n=>n.kind!=='mapping').map(n=>({need_id:n.id,reason:'No compatible fixture alternative'}))})}]};return{content:[{type:'text',text:'✅ Result\n\n'+JSON.stringify(args.input.schema?.fields.properties.selected?{selected:[{key:'@activepieces/piece-gmail:trigger:gmail_new_email_received',need_ids:['in'],reason:'receive'},{key:'@activepieces/piece-trello:action:create_card',need_ids:['out'],reason:'create'},{key:'@activepieces/piece-trello:action:get_card',need_ids:['proof'],reason:'verify'}],gaps:[]}:prompts.length===1?query:proposed)}]};}if(name==='ap_get_piece_props'){return {structuredContent:{piece:args.pieceName,name:args.actionOrTriggerName,expertNotes:['Native fixture note'],cardinality:'single'}};}if(name.startsWith('ap_search_'))return{structuredContent:{mode:'keyword',results:[]}};throw Error('Unexpected tool '+name);};
 const result=await designEmployee455({goal:actualGoal,companyContext:{confirmed:'example only'},catalogRows:rows,call,onPhase:async p=>phases.push(p)});
 check('Catalog reaches planner when native search is empty',()=>{assert.equal(result.status,'awaiting_connections');assert.equal(result.selected[1].actionName,'create_card');assert.ok(prompts[2].includes('description_ar'));assert.ok(prompts[2].includes('get_card'));assert.ok(prompts[2].includes('"idempotent":false'));assert.equal(result.catalogEvidence.operations,7201);assert.ok(result.discovery.filter(d=>d.need.kind!=='mapping').every(d=>d.modes.includes('curated_operations')));});
 check('Transient metadata read failure is recovered before planning',()=>assert.ok(fetchAttempts>1));
 check('Planner sees output paths and avoids Gmail subject path guessing',()=>{assert.ok(prompts[2].includes('message.subject'));assert.equal(result.selected[1].input.name,'{{trigger.message.subject}}');});
 check('Mapping stays in planner but is not treated as a missing tool',()=>{assert.ok(!prompts[1].includes('Map message fields to card fields'));assert.ok(prompts[2].includes('Map message fields to card fields'));assert.ok(result.selected[1].covers.includes('map'));});
 check('Operation selection uses structured native decisions before full planning',()=>{assert.equal(prompts.length,3);});
 prompts.length=0;businessFixtureIssues=[{type:'existing_system_unproven',step:'step_1',reason:'Fixture: source system is not established'}];const blocked=await designEmployee455({goal:actualGoal,companyContext:{confirmed:'example only'},catalogRows:rows,call});check('Business compatibility findings block otherwise valid construction',()=>{assert.equal(blocked.status,'needs_configuration');assert.ok(blocked.selectionRecovery.rejections.some(i=>i.type==='existing_system_unproven'));assert.equal(prompts.length,3);assert.equal(blocked.selected.length,0);assert.equal(blocked.selectionReview.stage,'before_planning');assert.ok(blocked.rejectedCandidates.length);});
}finally{globalThis.fetch=actualFetch;}
const report={passed:checks.length,checks,fixtures:'Native metadata snapshot, deterministic AI fixture; no live AI, provider execution, or business outcome claimed',phases};fs.writeFileSync(new URL('test-report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
